### ISSUE TITLE
Time offset

### ISSUE THREAD

**Issue by AlexKucera** [sebsel/kirby-micropub#19]
Hi Sebastian,

I noticed that posts created with your plugin have the wrong the creation time. 

Where does the plugin get the publish time from and can I set an offset somewhere?

**Comment by AlexKucera** [comment]
I solved I on my end by modifying endpoint.php and including `date_default_timezone_set('Europe/Berlin');` before the time gets generated if published isn't set. But ideally I'd like a configurable option instead of a code hack.

**Comment by sebsel** [comment]
Hmz, is that a hack? That's just setting the timezone, right?

Do you use [Kirby's](https://getkirby.com/docs/cheatsheet/options/timezone) `c::set('timezone','Europe/Berlin');` in your config.php? (It defaults to UTC.)

**Comment by AlexKucera** [comment]
No I don't. I guess I'm not up to date on my Kirby config knowledge. I had no idea that existed. :)

**Comment by sebsel** [comment]
Timezones are hard :)
For example, `2017-03-26 02:01:00` does not exist in Europe/Berlin, but it does in UTC. And worse: `2017-10-29 02:01:00` exists TWICE in Europe/Berlin, and just once in UTC. (Summertime / Daylight Saving Time, yeah)

For that reason, I like to store UTC on my server and change it to CET only for display.

Here's a snippet of what I use, and it's probably not the best way to do it, but this way I get the localisation of `strftime()` (printing Dutch months and weekdays, use `c::set('locale','nl_NL');`) and the timezone-support `strftime()` lacks:

```php
$cet = strtotime($entry->published()) +
  (new DateTime($entry->published()))
    ->setTimeZone(new DateTimeZone("Europe/Amsterdam"))
    ->format('Z');

echo strftime('%a %e %B %Y om %k:%M CET', $cet);
```

Hope that solves it!

**Comment by AlexKucera** [comment]
Setting the Kirby config solved it. 

Of course setting the time zone in PHP wasn't a hack. But it was hacking your code instead of using a more proper global config setting that might have already been there. Turns out there was. I was just looking in the wrong place. :)
